### PR TITLE
VFIN-1516: float editor group separator + VFIN-1519: QRegExp

### PR DESCRIPTION
**Pull request by tim-vdm**
Deze testen falen:

[error] 0.07% vfinance.test.test_connector.test_report_import.LoanReportImportCase.test_import_loan_account_schedules_report: 5.0408s
[error] 0.05% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_account_roles: 3.5773s
[error] 0.04% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_premium_schedules_report: 2.7412s
[error] 0.04% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_commissions_report: 2.7313s
[error] 0.04% vfinance.test.test_connector.test_report_import.LoanReportImportCase.test_import_loan_persons: 2.7022s
[error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_1_generate_reports_to_import: 0.1528s
[error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_3_import_account_roles_report: 0.0264s
[error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_4_import_account_assets_report: 0.0246s
[fail] 0.01% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_2_import_premium_schedules_report: 0.6368s

### CODE REVIEW

**Comment by erikjanss** [comment]
> Deze testen falen:
> 
> [error] 0.07% vfinance.test.test_connector.test_report_import.LoanReportImportCase.test_import_loan_account_schedules_report: 5.0408s
> [error] 0.05% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_account_roles: 3.5773s
> [error] 0.04% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_premium_schedules_report: 2.7412s
> [error] 0.04% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_commissions_report: 2.7313s
> [error] 0.04% vfinance.test.test_connector.test_report_import.LoanReportImportCase.test_import_loan_persons: 2.7022s
> [error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_1_generate_reports_to_import: 0.1528s
> [error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_3_import_account_roles_report: 0.0264s
> [error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_4_import_account_assets_report: 0.0246s
> [fail] 0.01% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_2_import_premium_schedules_report: 0.6368s

wat bedoel je hiermee ?  falen die testen omwille van de regexp of zo ?

**Comment by tim-vdm** [comment]
Ik denk niet dat het door mijn aanpassingen komt. Heb enkele testen lokaal gedraaid zonder mijn aanpassingen en dan falen deze ook. Mijn vraag is dus eerder: falen deze ook bij andere runs op Jenkins omdat er een PR gemerged is die deze testen doet falen?

**Comment by erikjanss** [comment]
ja, dat laatste is idd het geval
maar zou intussen in orde mtn zijn

**Comment by tim-vdm** [comment]
Testen zijn opnieuw aan het draaien voor de zekerheid...

**Comment by tim-vdm** [comment]
Tests passed

**Pull request merged**
